version: "3.8"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build: ./backend
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=change_me
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: ./backend
    command: celery -A app.celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
